ALTER TABLE dict_item
DROP
CONSTRAINT dict_item_dict_code_fkey;

CREATE TABLE chunks
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_id   VARCHAR(36)                             NOT NULL,
    chunk_index   INTEGER                                 NOT NULL,
    text          TEXT                                    NOT NULL,
    clause_number VARCHAR(50),
    parent_title  VARCHAR(500),
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_chunks PRIMARY KEY (id)
);

DROP TABLE dict_item CASCADE;

DROP TABLE dict_type CASCADE;